import dotenv from "dotenv";
import connectDB from "../src/config/db.js";
import carData from "../src/models/carData.model.js ";

dotenv.config();

const seedCardData = async () => {
	try {
		connectDB();

		await carData.deleteMany();

		await carData.create({
			brands: [
				"Maruti",
				"Hyundai",
				"Ford",
				"Renault",
				"Mini",
				"Mercedes-Benz",
				"Toyota",
				"Volkswagen",
				"Honda",
				"Mahindra",
				"Datsun",
				"Tata",
				"Kia",
				"BMW",
				"Audi",
				"Land Rover",
				"Jaguar",
				"MG",
				"Isuzu",
				"Porsche",
				"Skoda",
				"Volvo",
				"Lexus",
				"Jeep",
				"Maserati",
				"Bentley",
				"Nissan",
				"ISUZU",
				"Ferrari",
				"Mercedes-AMG",
				"Rolls-Royce",
				"Force",
			],

			models: [
				"Alto",
				"Grand",
				"i20",
				"Ecosport",
				"Wagon R",
				"i10",
				"Venue",
				"Swift",
				"Verna",
				"Duster",
				"Cooper",
				"Ciaz",
				"C-Class",
				"Innova",
				"Baleno",
				"Swift Dzire",
				"Vento",
				"Creta",
				"City",
				"Bolero",
				"Fortuner",
				"KWID",
				"Amaze",
				"Santro",
				"XUV500",
				"KUV100",
				"Ignis",
				"RediGO",
				"Scorpio",
				"Marazzo",
				"Aspire",
				"Figo",
				"Vitara",
				"Tiago",
				"Polo",
				"Seltos",
				"Celerio",
				"GO",
				"5",
				"CR-V",
				"Endeavour",
				"KUV",
				"Jazz",
				"3",
				"A4",
				"Tigor",
				"Ertiga",
				"Safari",
				"Thar",
				"Hexa",
				"Rover",
				"Eeco",
				"A6",
				"E-Class",
				"Q7",
				"Z4",
				"6",
				"XF",
				"X5",
				"Hector",
				"Civic",
				"D-Max",
				"Cayenne",
				"X1",
				"Rapid",
				"Freestyle",
				"Superb",
				"Nexon",
				"XUV300",
				"Dzire VXI",
				"S90",
				"WR-V",
				"XL6",
				"Triber",
				"ES",
				"Wrangler",
				"Camry",
				"Elantra",
				"Yaris",
				"GL-Class",
				"7",
				"S-Presso",
				"Dzire LXI",
				"Aura",
				"XC",
				"Ghibli",
				"Continental",
				"CR",
				"Kicks",
				"S-Class",
				"Tucson",
				"Harrier",
				"X3",
				"Octavia",
				"Compass",
				"CLS",
				"redi-GO",
				"Glanza",
				"Macan",
				"X4",
				"Dzire ZXI",
				"XC90",
				"F-PACE",
				"A8",
				"MUX",
				"GTC4Lusso",
				"GLS",
				"X-Trail",
				"XE",
				"XC60",
				"Panamera",
				"Alturas",
				"Altroz",
				"NX",
				"Carnival",
				"C",
				"RX",
				"Ghost",
				"Quattroporte",
				"Gurkha",
			],

			fuel_types: ["Petrol", "Diesel", "CNG", "LPG", "Electric"],

			transmission_types: ["Manual", "Automatic"],
		});
		console.log("CarData added successfully");
		process.exit();
	} catch (error) {
		console.log(error);
		process.exit(1);
	}
};

seedCardData();
